version: '3'
services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - 5432:5432
# pgadmin:
#   image: dpage/pgadmin4
#   ports:
#     - 8080:80
#   environment:
#     PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
#     PGADMIN_DEFAULT_PASSWORD: 'admin123'